Filter out future-dated sensor events
loudnate/xDripG5 pull request #191
Opened 2024-02-03 16:13 UTC by bjorkert

Implemented a filter in TransmitterManager to exclude future-dated sensor events before sending to Nightscout. The solution has been successfully tested with a real sensor.

Resolves https://github.com/LoopKit/Loop/issues/2087

2024-02-03 16:24 UTC, marionbarker commented
The person who tested this uses G6 sensors with Loop-dev.
* The SAGE pill was not poplulated
* They first examined Nightscout for future dates, see graphic below
* After removing future dates in Nightscout, the SAGE pill was populated with the age of the sensor

![Nightscout-Before-PR](https://github.com/LoopKit/CGMBLEKit/assets/19607791/1bb71d18-5988-427f-a2dd-a6e5389dc3c6)

After applying the code from this PR, a new sensor was started and the SAGE pill was populated without needing to remove future dates from Nightscout.

![SAGE-works-with-PR](https://github.com/LoopKit/CGMBLEKit/assets/19607791/106a776e-1d4c-4d4a-aa93-47e8fdff3b33)

2024-05-18 15:29 UTC, marionbarker commented
@ps2 Please respond. This is a work-around for the root cause, but it does work to provide SAGE correctly for Loop users with Nightscout.

2024-05-19 14:29 UTC, ps2 requested changes

2024-05-19 14:29 UTC, ps2 commented on CGMBLEKit/TransmitterManager.swift
> +        events = events.filter { event in
This is not fixing the underlying problem (incorrect parsing of message data earlier in the process).  Please add a comment that this is a stopgap fix for the issue (https://github.com/LoopKit/Loop/issues/2087) and add an error level log here that includes a string description of the `glucose` object.

2024-05-19 16:13 UTC, ps2 approved these changes

2024-05-19 16:13 UTC, merged

2024-05-19 16:13 UTC, ps2 commented
Thanks!